/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AOCMS;

import AOCMS.option;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Vidya Academy of Science and Technology
 */
public class analysis extends javax.swing.JFrame {
Connection cn=null;
Statement st=null;
ResultSet rs=null;
String sql="";

String opu="";
String cat="";
String ag="";
String gen="";
    /**
     * Creates new form analysis
     */
    public analysis() {
        initComponents();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabl = new javax.swing.JTable();
        disp = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        all = new javax.swing.JCheckBox();
        name = new javax.swing.JCheckBox();
        cr_number = new javax.swing.JCheckBox();
        op_number = new javax.swing.JCheckBox();
        date = new javax.swing.JCheckBox();
        age = new javax.swing.JCheckBox();
        category = new javax.swing.JCheckBox();
        gender = new javax.swing.JCheckBox();
        reference = new javax.swing.JCheckBox();
        opunit = new javax.swing.JCheckBox();
        diagnosis = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        op_unit = new javax.swing.JCheckBox();
        cases = new javax.swing.JComboBox<>();
        count = new javax.swing.JCheckBox();
        agebox = new javax.swing.JCheckBox();
        agevalue = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        genderbox = new javax.swing.JCheckBox();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        datebox = new javax.swing.JCheckBox();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        op_unitcombo = new javax.swing.JComboBox<>();
        agecombo = new javax.swing.JComboBox<>();
        jSeparator6 = new javax.swing.JSeparator();
        daycombo = new javax.swing.JComboBox<>();
        monthcombo = new javax.swing.JComboBox<>();
        yearcombo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        and1 = new javax.swing.JLabel();
        day = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        month = new javax.swing.JLabel();
        agevalue2 = new javax.swing.JTextField();
        c = new javax.swing.JRadioButton();
        o = new javax.swing.JRadioButton();
        s = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        search = new javax.swing.JLabel();
        clear = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tabl.setBackground(new java.awt.Color(204, 204, 255));
        tabl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tabl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabl.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tabl);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1060, 570));

        disp.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        disp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 460, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AOCMS/1491425454_back_on_top.png"))); // NOI18N
        jLabel8.setToolTipText("Back to the Analysis Page");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 11)); // NOI18N
        jLabel9.setText("Back");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 1, 11)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AOCMS/exp.png"))); // NOI18N
        jLabel11.setText("<html>\n<b>\n<bold>EXPORT</bold>\n</b>\n</html>");
        jLabel11.setToolTipText("Click here to save this as Excel File");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 110, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1060, 630));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AOCMS/vidya2.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, 180, 130));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setForeground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("| Powered By: CSE-Vidya Academy Of Science And Technology, Thalakkottukara Thrissur |");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 570, 20));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 1160, 20));

        jLabel14.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 48)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AOCMS/medlogo.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 100, 120));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jLabel18.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("| _ |");
        jLabel18.setToolTipText("Minimize the screen");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 40, 30));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("| AOCMS | ANALYSIS |");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 30));

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("| X |");
        jLabel16.setToolTipText("Exit from AOCMS");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 50, 30));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("| Government Medical College, Mulankunnathukavu  Thrissur |");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 410, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AOCMS/logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 140, 120));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        all.setBackground(new java.awt.Color(204, 204, 255));
        all.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        all.setText("All Details");
        all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allActionPerformed(evt);
            }
        });
        jPanel1.add(all, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        name.setBackground(new java.awt.Color(204, 204, 255));
        name.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        name.setText("Name");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        cr_number.setBackground(new java.awt.Color(204, 204, 255));
        cr_number.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cr_number.setText("CR Number");
        jPanel1.add(cr_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        op_number.setBackground(new java.awt.Color(204, 204, 255));
        op_number.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        op_number.setText("OP Number");
        jPanel1.add(op_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        date.setBackground(new java.awt.Color(204, 204, 255));
        date.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        date.setText("Date");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        age.setBackground(new java.awt.Color(204, 204, 255));
        age.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        age.setText("Age");
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        category.setBackground(new java.awt.Color(204, 204, 255));
        category.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        category.setText("Category");
        jPanel1.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        gender.setBackground(new java.awt.Color(204, 204, 255));
        gender.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        gender.setText("Gender");
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        reference.setBackground(new java.awt.Color(204, 204, 255));
        reference.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        reference.setText("Reference");
        jPanel1.add(reference, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        opunit.setBackground(new java.awt.Color(204, 204, 255));
        opunit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        opunit.setText("OP Unit");
        jPanel1.add(opunit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        diagnosis.setBackground(new java.awt.Color(204, 204, 255));
        diagnosis.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        diagnosis.setText("Diagnosis");
        jPanel1.add(diagnosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, 310));

        op_unit.setBackground(new java.awt.Color(204, 204, 255));
        op_unit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        op_unit.setText("OP Unit");
        op_unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_unitActionPerformed(evt);
            }
        });
        jPanel1.add(op_unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        cases.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cases.setModel(new DefaultComboBoxModel());
        cases.setToolTipText("");
        cases.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                casesItemStateChanged(evt);
            }
        });
        cases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casesMouseClicked(evt);
            }
        });
        cases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casesActionPerformed(evt);
            }
        });
        jPanel1.add(cases, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 160, -1));

        count.setBackground(new java.awt.Color(204, 204, 255));
        count.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        count.setText("Count");
        count.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countActionPerformed(evt);
            }
        });
        jPanel1.add(count, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 110, -1));

        agebox.setBackground(new java.awt.Color(204, 204, 255));
        agebox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        agebox.setText("Age");
        agebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageboxActionPerformed(evt);
            }
        });
        jPanel1.add(agebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        agevalue.setBackground(new java.awt.Color(204, 204, 255));
        agevalue.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        agevalue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        agevalue.setBorder(null);
        jPanel1.add(agevalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 50, 30));

        jSeparator4.setBackground(new java.awt.Color(204, 204, 255));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 50, 10));

        genderbox.setBackground(new java.awt.Color(204, 204, 255));
        genderbox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        genderbox.setText("Gender");
        genderbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderboxActionPerformed(evt);
            }
        });
        jPanel1.add(genderbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, -1, -1));

        male.setBackground(new java.awt.Color(204, 204, 255));
        male.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, -1, -1));

        female.setBackground(new java.awt.Color(204, 204, 255));
        female.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, -1, -1));

        jLabel4.setBackground(new java.awt.Color(153, 255, 102));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("<html><body><Center>Click on the columns to be displayed:</center></body></html>");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 230, -1));

        jSeparator7.setBackground(new java.awt.Color(204, 204, 255));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 230, 10));

        jLabel5.setBackground(new java.awt.Color(153, 255, 102));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Conditions");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 230, -1));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 230, 10));

        datebox.setBackground(new java.awt.Color(204, 204, 255));
        datebox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        datebox.setText("Date");
        datebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateboxActionPerformed(evt);
            }
        });
        jPanel1.add(datebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, -1, -1));

        jSeparator12.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 230, 10));

        jSeparator8.setForeground(new java.awt.Color(153, 0, 153));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 340, 10));

        op_unitcombo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        op_unitcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oncology", "Chest Pulmonary Medicine", "ART" }));
        op_unitcombo.setSelectedIndex(-1);
        op_unitcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_unitcomboActionPerformed(evt);
            }
        });
        jPanel1.add(op_unitcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 160, -1));

        agecombo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        agecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equal To", "Greater Than", "Less Than", "Between Two Values" }));
        agecombo.setSelectedIndex(-1);
        agecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agecomboActionPerformed(evt);
            }
        });
        jPanel1.add(agecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 160, -1));

        jSeparator6.setBackground(new java.awt.Color(204, 204, 255));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 50, 10));

        daycombo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        daycombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        daycombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daycomboActionPerformed(evt);
            }
        });
        jPanel1.add(daycombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 70, -1));

        monthcombo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        monthcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        monthcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthcomboActionPerformed(evt);
            }
        });
        jPanel1.add(monthcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 70, -1));

        yearcombo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        yearcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        yearcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearcomboActionPerformed(evt);
            }
        });
        jPanel1.add(yearcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 70, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Enter the age:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Select the OP Unit:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, 20));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("Select the Category:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, 30));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setText("Select the Case:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, 20));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("Select the condition:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, 30));

        and1.setBackground(new java.awt.Color(204, 204, 255));
        and1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        and1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        and1.setText("and");
        jPanel1.add(and1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 40, -1));

        day.setBackground(new java.awt.Color(204, 204, 255));
        day.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        day.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        day.setText("Day");
        jPanel1.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 30, -1));

        year.setBackground(new java.awt.Color(204, 204, 255));
        year.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        year.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        year.setText("Year");
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 260, 60, -1));

        month.setBackground(new java.awt.Color(204, 204, 255));
        month.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        month.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        month.setText("Month");
        jPanel1.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 60, -1));

        agevalue2.setBackground(new java.awt.Color(204, 204, 255));
        agevalue2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        agevalue2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        agevalue2.setBorder(null);
        jPanel1.add(agevalue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 50, 30));

        c.setBackground(new java.awt.Color(204, 204, 255));
        c.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c.setText("C");
        c.setToolTipText("Casuality");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        jPanel1.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 40, 30));

        o.setBackground(new java.awt.Color(204, 204, 255));
        o.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        o.setText("O");
        o.setToolTipText("OP");
        o.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oActionPerformed(evt);
            }
        });
        jPanel1.add(o, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 40, 30));

        s.setBackground(new java.awt.Color(204, 204, 255));
        s.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        s.setText("S");
        s.setToolTipText("Speciality");
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });
        jPanel1.add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 910, 310));

        jLabel6.setBackground(new java.awt.Color(204, 204, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AOCMS/1491425454_back_on_top.png"))); // NOI18N
        jLabel6.setToolTipText("Back to the Main Page");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 30, 50));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Back");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, -1, -1));

        jLabel3.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("Automated OP Counter Management System");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        search.setBackground(new java.awt.Color(204, 204, 255));
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AOCMS/search.png"))); // NOI18N
        search.setToolTipText("Search ");
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, 70, 80));

        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AOCMS/1491430428_Backspace_erase_delete_back.png"))); // NOI18N
        clear.setToolTipText("Clear the selections & texts completely");
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, 50, 50));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setText("Clear");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 590, -1, -1));

        jLabel10.setBackground(new java.awt.Color(204, 204, 255));
        jLabel10.setForeground(new java.awt.Color(153, 255, 102));
        jLabel10.setText("jLabel10");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 910, 520));

        jLabel2.setBackground(new java.awt.Color(102, 0, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AOCMS/blue.jpg"))); // NOI18N
        jLabel2.setOpaque(true);
        jLabel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel2FocusGained(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1070, 650));

        setSize(new java.awt.Dimension(1060, 680));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        String timeStamp = new SimpleDateFormat("dd-MM-yyyy").format(Calendar.getInstance().getTime());
        try{
    PrintWriter writer = new PrintWriter("date.txt", "UTF-8");
    writer.println();
    writer.close();
       } catch (IOException e) {}
        
        System.exit(0);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel2FocusGained

    }//GEN-LAST:event_jLabel2FocusGained

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:

        option op=new option();
        op.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
jLabel15.setVisible(false);
jLabel19.setVisible(false);
jLabel20.setVisible(false);
op_unitcombo.setVisible(false);

cases.setVisible(false);

jLabel22.setVisible(false);
jLabel13.setVisible(false);
agecombo.setVisible(false);
agevalue.setVisible(false);
agevalue2.setVisible(false);
jSeparator4.setVisible(false);
jSeparator6.setVisible(false);
and1.setVisible(false);
c.setVisible(false);
o.setVisible(false);
s.setVisible(false);

male.setVisible(false);
female.setVisible(false);

daycombo.setVisible(false);
monthcombo.setVisible(false);
yearcombo.setVisible(false);
day.setVisible(false);
month.setVisible(false);
year.setVisible(false);


        String timeStamp = new SimpleDateFormat("yyyy").format(Calendar.getInstance().getTime());

jPanel2.setVisible(false);



buttonGroup4.add(male);
buttonGroup4.add(female);
buttonGroup1.add(c);
buttonGroup1.add(o);
buttonGroup1.add(s);

cases.setVisible(false);
DefaultComboBoxModel cm=(DefaultComboBoxModel) daycombo.getModel();
cm.removeAllElements();
cm.addElement("NULL");
for(int i=1;i<=31;i++)
cm.addElement(i);
daycombo.setModel(cm); 

DefaultComboBoxModel ccm=(DefaultComboBoxModel) monthcombo.getModel();
ccm.removeAllElements();
ccm.addElement("NULL");
ccm.addElement("JAN");
ccm.addElement("FEB");
ccm.addElement("MAR");
ccm.addElement("APR");
ccm.addElement("MAY");
ccm.addElement("JUN");
ccm.addElement("JUL");
ccm.addElement("AUG");
ccm.addElement("SEP");
ccm.addElement("OCT");
ccm.addElement("NOV");
ccm.addElement("DEC");
monthcombo.setModel(ccm); 
 
DefaultComboBoxModel ym=(DefaultComboBoxModel) yearcombo.getModel();
ym.removeAllElements();
ym.addElement("NULL");
for(int i=(Integer.parseInt(timeStamp));i>1990;i--)
ym.addElement(i);
yearcombo.setModel(ym); 

   
    }//GEN-LAST:event_formComponentShown

    private void op_unitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_unitActionPerformed

        if(op_unit.isSelected())
{
    jLabel15.setVisible(true);
op_unitcombo.setVisible(true);

}
else
{
    c.setVisible(false);
o.setVisible(false);
s.setVisible(false);
jLabel15.setVisible(false);
jLabel19.setVisible(false);
jLabel20.setVisible(false);
op_unitcombo.setVisible(false);
cases.setVisible(false);
op_unitcombo.setSelectedIndex(-1);
cases.setSelectedIndex(-1);

}

    }//GEN-LAST:event_op_unitActionPerformed

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked


   
try
{
   //Establish connection to the MySQL Database
Class.forName("java.sql.Driver");	
cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/aocms","root","*********");

	
sql="select * from patients;";
	st=cn.createStatement();
	rs=st.executeQuery(sql);
	rs.next();
  String query="select ";                       

            
                
            if(name.isSelected())
                                query=query.concat(" name ,");
            if(cr_number.isSelected())
                                query=query.concat(" cr_number ,");
            if(op_number.isSelected())
                                query=query.concat(" op_number ,");
            if(age.isSelected())
                                query=query.concat(" age ,");
            if(category.isSelected())
                                query=query.concat(" category ,");
            if(gender.isSelected())
                                query=query.concat(" gender ,");
            if(reference.isSelected())
                                query=query.concat(" referenced_by ,");
            if(opunit.isSelected())
                                query=query.concat(" op_unit ,");
            if(diagnosis.isSelected())
                                query=query.concat(" diagnosis ,");
            if(date.isSelected())
                                query=query.concat(" date ,");
            if(all.isSelected())
                                query=query.concat(" *,");
            if(count.isSelected())
                                query=query.concat(" count(*),");
            
            
             if(query.charAt(query.length() - 1)==',')
        {
          query = query.substring(0, query.length()-1);
          query=query.concat(" from patients ");
        }
         if(op_unit.isSelected())
         {
             if(!agebox.isSelected()||!datebox.isSelected()||!genderbox.isSelected())
                query=query.concat("where "+opu);
             else
                query=query.concat("&& "+opu);
            
             if(o.isSelected()||c.isSelected()||s.isSelected())
         {
             query=query.concat(cat);
         }
             
             if(!cases.getSelectedItem().equals("ALL"))
             {
                query=query.concat(" && diagnosis =\""+cases.getSelectedItem()+"\""); 
             }
         }
         
         if(agebox.isSelected())
         {
             if(!agecombo.getSelectedItem().equals("Between Two Values"))
            {
                 if(op_unit.isSelected()||datebox.isSelected()||genderbox.isSelected())
                 query=query.concat("&& age "+ag+" "+agevalue.getText());
                 else
                 query=query.concat("where age "+ag+" "+agevalue.getText());
            }
             else
             {
                if(op_unit.isSelected()||datebox.isSelected()||genderbox.isSelected())
                 query=query.concat("&& age between "+agevalue.getText()+" and "+agevalue2.getText());
                 else
                 query=query.concat("where age between "+agevalue.getText()+" and "+agevalue2.getText());
             }
             }
         
             if(genderbox.isSelected())
         {
             if(agebox.isSelected()||datebox.isSelected()||op_unit.isSelected())
             { query=query.concat("&& gender =\""+gen+"\"");}
            
             else
             {  query=query.concat("where gender =\""+gen+"\"");}
         }
             if(datebox.isSelected())
         {
             if(agebox.isSelected()||genderbox.isSelected()||op_unit.isSelected())
             {
                  if(!daycombo.getSelectedItem().equals("NULL"))
                      query=query.concat("&& day(date)="+daycombo.getSelectedItem());
                  if(!monthcombo.getSelectedItem().equals("NULL"))
                      query=query.concat("&& month(date)="+monthcombo.getSelectedIndex());
                  if(!yearcombo.getSelectedItem().equals("NULL"))
                      query=query.concat("&& year(date)="+yearcombo.getSelectedItem());
             }
             else
             {
                  if(!daycombo.getSelectedItem().equals("NULL"))
                  query=query.concat("where day(date)="+daycombo.getSelectedItem());
                  if(!monthcombo.getSelectedItem().equals("NULL"))
                  {
                      if(!daycombo.getSelectedItem().equals("NULL"))
                          query=query.concat("&& month(date)="+monthcombo.getSelectedIndex());
                      else
                          query=query.concat("where month(date)="+monthcombo.getSelectedIndex());
                  }
                      
                  if(!yearcombo.getSelectedItem().equals("NULL"))
                  {
                      if(!daycombo.getSelectedItem().equals("NULL")||!monthcombo.getSelectedItem().equals("NULL"))
                          query=query.concat("&& year(date)="+yearcombo.getSelectedItem());
                      else
                          query=query.concat("where year(date)="+yearcombo.getSelectedItem());
                  }
             }
         }
             

sql=query;
st=cn.createStatement();
rs=st.executeQuery(sql);
  TableModel model = DbUtils.resultSetToTableModel(rs);
tabl.setModel(model);
     disp.setText("Your Search Result:");
        jPanel2.setVisible(true);
        jPanel1.setVisible(false);
        
}

//To prevent the program from crashing if there are anyother errors and to find out details of the error
catch(Exception e)
{
JOptionPane.showMessageDialog(null,"Please ensure that no field is left blank!","Warning!",JOptionPane.INFORMATION_MESSAGE);	
   
             
}


        
    }//GEN-LAST:event_searchMouseClicked

    private void allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allActionPerformed
if(all.isSelected())
{
    name.setEnabled(false);
     cr_number.setEnabled(false);
      op_number.setEnabled(false);
       age.setEnabled(false);
        category.setEnabled(false);
        gender.setEnabled(false);
        reference.setEnabled(false);
        opunit.setEnabled(false);
        diagnosis.setEnabled(false);
        date.setEnabled(false);
        name.setSelected(false);
     cr_number.setSelected(false);
      op_number.setSelected(false);
       age.setSelected(false);
        category.setSelected(false);
        gender.setSelected(false);
        reference.setSelected(false);
        opunit.setSelected(false);
        diagnosis.setSelected(false);
        date.setSelected(false);
        
        
}

else
{
      name.setEnabled(true);
     cr_number.setEnabled(true);
      op_number.setEnabled(true);
       age.setEnabled(true);
        category.setEnabled(true);
        date.setEnabled(true);
        gender.setEnabled(true);
        reference.setEnabled(true);
        opunit.setEnabled(true);
        diagnosis.setEnabled(true);
}
    }//GEN-LAST:event_allActionPerformed

    private void casesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casesActionPerformed
  
    }//GEN-LAST:event_casesActionPerformed

    private void casesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_casesMouseClicked

    private void casesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_casesItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_casesItemStateChanged

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

        this.dispose();
        analysis op=new analysis();
        op.setVisible(true);
       
    }//GEN-LAST:event_jLabel8MouseClicked

    private void ageboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageboxActionPerformed
if(agebox.isSelected())
{
jLabel22.setVisible(true);
jLabel13.setVisible(true);
agecombo.setVisible(true);
agevalue.setVisible(true);
jSeparator6.setVisible(true);

}
if(!agebox.isSelected())
{

agevalue.setVisible(false);
agevalue2.setVisible(false);
jSeparator4.setVisible(false);
and1.setVisible(false);
agevalue.setText("");
agevalue2.setText("");
jSeparator6.setVisible(false);
jLabel22.setVisible(false);
jLabel13.setVisible(false);
agecombo.setVisible(false);
agecombo.setSelectedIndex(-1);

}
    // TODO add your handling code here:
    }//GEN-LAST:event_ageboxActionPerformed

    private void genderboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderboxActionPerformed
if(genderbox.isSelected())
{
    male.setVisible(true);
    female.setVisible(true);
}
else
{
    male.setVisible(false);
    female.setVisible(false);
    buttonGroup4.clearSelection();
    
}
// TODO add your handling code here:
    }//GEN-LAST:event_genderboxActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
gen="M";   // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
gen="F";
   // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void dateboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateboxActionPerformed
if(datebox.isSelected())
{
    daycombo.setVisible(true);
monthcombo.setVisible(true);
yearcombo.setVisible(true);
day.setVisible(true);
month.setVisible(true);
year.setVisible(true);
}
else
{
daycombo.setVisible(false);
monthcombo.setVisible(false);
yearcombo.setVisible(false);
day.setVisible(false);
month.setVisible(false);
year.setVisible(false);
daycombo.setSelectedIndex(0);
monthcombo.setSelectedIndex(0);
yearcombo.setSelectedIndex(0);
}
    }//GEN-LAST:event_dateboxActionPerformed

    private void countActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countActionPerformed
if(count.isSelected())
{
    name.setEnabled(false);
     cr_number.setEnabled(false);
      op_number.setEnabled(false);
       age.setEnabled(false);
        category.setEnabled(false);
        gender.setEnabled(false);
        reference.setEnabled(false);
        opunit.setEnabled(false);
        diagnosis.setEnabled(false);
        date.setEnabled(false);
        name.setSelected(false);
     cr_number.setSelected(false);
      op_number.setSelected(false);
       age.setSelected(false);
        category.setSelected(false);
        gender.setSelected(false);
        reference.setSelected(false);
        opunit.setSelected(false);
        diagnosis.setSelected(false);
        date.setSelected(false);
        
        
}

else
{
      name.setEnabled(true);
     cr_number.setEnabled(true);
      op_number.setEnabled(true);
       age.setEnabled(true);
        category.setEnabled(true);
        date.setEnabled(true);
        gender.setEnabled(true);
        reference.setEnabled(true);
        opunit.setEnabled(true);
        diagnosis.setEnabled(true);
}        // TODO add your handling code here:
    }//GEN-LAST:event_countActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
try{
                //the file path
               File file = new File("D:\\Desktop\\History.xls");
               //if the file not exist create one
               if(!file.exists()){
                   file.createNewFile();
               }
               
    try (FileWriter fw = new FileWriter(file.getAbsoluteFile())) {
        BufferedWriter bw = new BufferedWriter(fw);
       
       
        for(int i=0;i<tabl.getColumnCount();i++)
        {
            fw.write(tabl.getColumnName(i)+"\t");
        }
        fw.write("\n");
        for(int i = 0; i < tabl.getRowCount(); i++){
           
            for(int j = 0; j < tabl.getColumnCount(); j++){
                bw.write(tabl.getModel().getValueAt(i, j)+"\t ");
            }
         
            bw.write("\n");
        }
      
        bw.close();
       
    }
               JOptionPane.showMessageDialog(null, "Data Exported");
               
               }catch(Exception ex){
                   ex.printStackTrace();
               }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void op_unitcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_unitcomboActionPerformed
opu="op_unit=\""+op_unitcombo.getSelectedItem()+"\"";
        if(op_unitcombo.getSelectedItem().equals("Oncology"))
{
    
    o.setVisible(true);
    s.setVisible(true); 
    c.setVisible(true);
    jLabel19.setVisible(true);
    
   
}
else if(op_unitcombo.getSelectedItem().equals("Chest Pulmonary Medicine")||op_unitcombo.getSelectedItem().equals("ART"))
{
    buttonGroup1.clearSelection();
    cases.setSelectedIndex(-1);
     o.setVisible(false);
    s.setVisible(false); 
    c.setVisible(false);
    jLabel19.setVisible(false);
    cases.setVisible(false);
     jLabel20.setVisible(false);
}

    }//GEN-LAST:event_op_unitcomboActionPerformed

    private void agecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agecomboActionPerformed
 if(agecombo.getSelectedItem().equals("Equal To"))
{
      agevalue2.setVisible(false);
      jSeparator4.setVisible(false);
       and1.setVisible(false);
       ag=" = ";
     
         
} 
        if(agecombo.getSelectedItem().equals("Greater Than"))
{
     agevalue2.setVisible(false);
      jSeparator4.setVisible(false);
      and1.setVisible(false);
      ag=" >= ";
      
     

}
 if(agecombo.getSelectedItem().equals("Less Than"))
{
     agevalue2.setVisible(false);
      jSeparator4.setVisible(false);
       and1.setVisible(false);
     ag=" <= ";
  
} 
 if(agecombo.getSelectedItem().equals("Between Two Values"))
{
     agevalue2.setVisible(true);
      jSeparator4.setVisible(true);
       and1.setVisible(true);
     
      
} 


// Equal ToGreater ThanLess ThanBetween Two Values
    }//GEN-LAST:event_agecomboActionPerformed

    private void daycomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daycomboActionPerformed
    

        // TODO add your handling code here:
    }//GEN-LAST:event_daycomboActionPerformed

    private void monthcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthcomboActionPerformed
  // TODO add your handling code here:
    }//GEN-LAST:event_monthcomboActionPerformed

    private void yearcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearcomboActionPerformed

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
      this.dispose();
      analysis an=new analysis();
      an.setVisible(true);
    }//GEN-LAST:event_clearMouseClicked

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
cat=" && category =\"Casuality\"";
        DefaultComboBoxModel dcm=(DefaultComboBoxModel) cases.getModel();
dcm.removeAllElements();
dcm.addElement("ALL");
cases.setModel(dcm); 
cases.setVisible(false);       

    }//GEN-LAST:event_cActionPerformed

    private void oActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oActionPerformed
cat=cat=" && category =\"OP\"";
        if(o.isSelected())
{
    jLabel20.setVisible(true);
cases.setVisible(true);
    DefaultComboBoxModel dcm=(DefaultComboBoxModel) cases.getModel();
dcm.removeAllElements();
dcm.addElement("ALL");
dcm.addElement("NULL");
dcm.addElement("Test Case ");
dcm.addElement("Test Case ");
dcm.addElement("Test Case ");
dcm.addElement("Test Case ");
dcm.addElement("Test Case ");
dcm.addElement("Test Case ");
dcm.addElement("Test Case ");
dcm.addElement("Test Case ");

cases.setModel(dcm);   
}
    }//GEN-LAST:event_oActionPerformed

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
cat=" && category =\"Speciality\"";
        if(s.isSelected())
{
    DefaultComboBoxModel dcm=(DefaultComboBoxModel) cases.getModel();
dcm.removeAllElements();
   jLabel20.setVisible(true);
cases.setVisible(true);
   dcm.addElement("ALL");
   dcm.addElement("NULL");
   dcm.addElement("Test Case ");
dcm.addElement("Test Case ");
dcm.addElement("Test Case ");
dcm.addElement("Test Case ");
dcm.addElement("Test Case ");
dcm.addElement("Test Case ");
dcm.addElement("Test Case ");
dcm.addElement("Test Case ");

cases.setModel(dcm); 
}
    }//GEN-LAST:event_sActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new analysis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox age;
    private javax.swing.JCheckBox agebox;
    private javax.swing.JComboBox<String> agecombo;
    private javax.swing.JTextField agevalue;
    private javax.swing.JTextField agevalue2;
    private javax.swing.JCheckBox all;
    private javax.swing.JLabel and1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JRadioButton c;
    private javax.swing.JComboBox<String> cases;
    private javax.swing.JCheckBox category;
    private javax.swing.JLabel clear;
    private javax.swing.JCheckBox count;
    private javax.swing.JCheckBox cr_number;
    private javax.swing.JCheckBox date;
    private javax.swing.JCheckBox datebox;
    private javax.swing.JLabel day;
    private javax.swing.JComboBox<String> daycombo;
    private javax.swing.JCheckBox diagnosis;
    private javax.swing.JLabel disp;
    private javax.swing.JRadioButton female;
    private javax.swing.JCheckBox gender;
    private javax.swing.JCheckBox genderbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JRadioButton male;
    private javax.swing.JLabel month;
    private javax.swing.JComboBox<String> monthcombo;
    private javax.swing.JCheckBox name;
    private javax.swing.JRadioButton o;
    private javax.swing.JCheckBox op_number;
    private javax.swing.JCheckBox op_unit;
    private javax.swing.JComboBox<String> op_unitcombo;
    private javax.swing.JCheckBox opunit;
    private javax.swing.JCheckBox reference;
    private javax.swing.JRadioButton s;
    private javax.swing.JLabel search;
    private javax.swing.JTable tabl;
    private javax.swing.JLabel year;
    private javax.swing.JComboBox<String> yearcombo;
    // End of variables declaration//GEN-END:variables
}
