/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AOCMS;


import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Calendar;



public class option extends javax.swing.JFrame {
static int tokenvalue;
    

    
    /**
     * Creates new form option
     */
    public option() {
       
        initComponents();
    }
    
   
    /**
     * Creates new form JavaListBox1
     */
   
    public option(int tokenvalue)
{
      initComponents();
      String tok="";
      try (BufferedReader br1 = new BufferedReader(new FileReader("token.txt"))) {

			String stoken;
			while ((stoken = br1.readLine()) != null) {
						tok=stoken;}

		} catch (IOException e) {
			e.printStackTrace();
		}
      tokenvalue=Integer.parseInt(tok);
  
     option.tokenvalue=tokenvalue;
     
     
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        token2 = new javax.swing.JLabel();
        token6 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        token5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        token3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        token = new javax.swing.JLabel();
        token1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("| Powered By: CSE-Vidya Academy Of Science And Technology, Thalakkottukara Thrissur |");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 570, 20));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 1060, 20));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 48)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AOCMS/medlogo.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 100, 110));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AOCMS/vidya2.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 180, 130));

        token2.setFont(new java.awt.Font("High Tower Text", 0, 24)); // NOI18N
        token2.setForeground(new java.awt.Color(102, 0, 0));
        token2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        token2.setText("Tokens Taken");
        jPanel1.add(token2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 210, -1));

        token6.setFont(new java.awt.Font("High Tower Text", 0, 24)); // NOI18N
        token6.setForeground(new java.awt.Color(102, 0, 0));
        token6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        token6.setText("Exisiting Patient ");
        jPanel1.add(token6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, 210, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 340, 10));

        token5.setFont(new java.awt.Font("High Tower Text", 0, 24)); // NOI18N
        token5.setForeground(new java.awt.Color(102, 0, 0));
        token5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        token5.setText("Analysis");
        jPanel1.add(token5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, 210, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AOCMS/old.png"))); // NOI18N
        jLabel15.setToolTipText("<html>\nclick here to:<br>\n1) View an Existing Patient record<br>\n2) Create a Token<br>\n3) Update/Edit saved records<br>\n</html>");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 240, 220));

        token3.setFont(new java.awt.Font("High Tower Text", 0, 24)); // NOI18N
        token3.setForeground(new java.awt.Color(102, 0, 0));
        token3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        token3.setText("New Patient");
        jPanel1.add(token3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 310, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AOCMS/analysis.png"))); // NOI18N
        jLabel14.setToolTipText("<html>\nClick here to:<br>\n1) See complete analysis of patient recordst<br>\n2) Save it to MS Excel <br>\n</html>");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 150, 150));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AOCMS/new.png"))); // NOI18N
        jLabel21.setToolTipText("<html> Click here to:<br> 1) Register a New Patient<br> 2) Create a Token<br> 3) Produce an OP Ticket<br> </html>");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 260, 250));

        jLabel3.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Automated OP Counter Management System");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        token.setBackground(new java.awt.Color(102, 18, 25));
        token.setFont(new java.awt.Font("Tempus Sans ITC", 1, 60)); // NOI18N
        token.setForeground(new java.awt.Color(0, 153, 153));
        token.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        token.setToolTipText("Number of tokens taken today");
        jPanel1.add(token, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 210, 220));

        token1.setFont(new java.awt.Font("High Tower Text", 0, 24)); // NOI18N
        token1.setForeground(new java.awt.Color(102, 0, 0));
        token1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        token1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AOCMS/tok.gif"))); // NOI18N
        jPanel1.add(token1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 250, 230));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AOCMS/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 140, 120));

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AOCMS/1.jpg"))); // NOI18N
        jLabel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel2ComponentShown(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 1060, 630));

        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 290, 280));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 30, 1110, 630));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jLabel18.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("| _ ");
        jLabel18.setToolTipText("Minimize the screen");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 40, 30));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("| AOCMS |");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("| X |");
        jLabel16.setToolTipText("Exit AOCMS");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 60, 30));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("| Government Medical College, Mulankunnathukavu  Thrissur |");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 410, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
 
        String tok="";
        try(BufferedReader br = new BufferedReader(new FileReader("token.txt"))) {
			String sCurrentLine;
			while ((sCurrentLine = br.readLine()) != null) 
                        {
                            tok=sCurrentLine;
                	}

		} catch (IOException e) {
			e.printStackTrace();
		}
tokenvalue=Integer.parseInt(tok);
if(tokenvalue>=1)
{
    token.setText("0");
   
}
token.setText(""+tokenvalue);
 
    }//GEN-LAST:event_formComponentShown

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        
       analysis an=new analysis();
        an.setVisible(true);
       this.setVisible(false); 
   
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
  String timeStamp = new SimpleDateFormat("dd-MM-yyyy").format(Calendar.getInstance().getTime());
        try{
    PrintWriter writer = new PrintWriter("date.txt", "UTF-8");
    writer.println(timeStamp);
    writer.close();
       } catch (IOException e) {}
        
        System.exit(0);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
    setState(ICONIFIED);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
      NewPatient np=new NewPatient();
        new NewPatient(tokenvalue).setVisible(true);
       this.setVisible(false);
       
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2ComponentShown

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
 OldPatient op=new OldPatient();
        new OldPatient(tokenvalue).setVisible(true);
       this.setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new option().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel token;
    private javax.swing.JLabel token1;
    private javax.swing.JLabel token2;
    private javax.swing.JLabel token3;
    private javax.swing.JLabel token5;
    private javax.swing.JLabel token6;
    // End of variables declaration//GEN-END:variables
}
